runtime: nodejs20
env: standard
env_variables:
  HTTPS_PORT: "8443"
  HTTP_PORT: "8080"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "test"
  DB_NAME: "postgres"
  SSL_KEY_PATH: "./key.pem"
  SSL_CERT_PATH: "./cert.pem"
  SESSION_SECRET: "not_so_secret_key_372"
  FIREBASE_API_KEY: "AIzaSyChDNNrQ046SWLRYpF5wedrImchtUgkfc4"
  FIREBASE_AUTH_DOMAIN: "cmpt-372-project-31c8f.firebaseapp.com"
  FIREBASE_PROJECT_ID: "cmpt-372-project-31c8f"
  FIREBASE_STORAGE_BUCKET: "cmpt-372-project-31c8f.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "162071106344"
  FIREBASE_APP_ID: "1:162071106344:web:c90d25dcf24b145ee8b61d"
  FIREBASE_MEASUREMENT_ID: "G-J6JM6GWW3B"
